"""user email_verified

Revision ID: 323eb73d463c
Revises: 819ed5ff183e
Create Date: 2026-07-17 05:32:23.391178
"""
from alembic import op
import sqlalchemy as sa


revision = '323eb73d463c'
down_revision = '819ed5ff183e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default so existing rows get a value; existing accounts are treated as
        # unverified (they can still sign in unless REQUIRE_EMAIL_VERIFICATION is on).
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
