"""workspace ingest key

Revision ID: 819ed5ff183e
Revises: 49e8ab812556
Create Date: 2026-07-17 00:25:59.721254
"""
from alembic import op
import sqlalchemy as sa


revision = '819ed5ff183e'
down_revision = '49e8ab812556'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingest_key_hash', sa.String(length=128), nullable=False))
        batch_op.create_index(batch_op.f('ix_workspaces_ingest_key_hash'), ['ingest_key_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_ingest_key_hash'))
        batch_op.drop_column('ingest_key_hash')

    # ### end Alembic commands ###
