"""workspaces + tenancy

Revision ID: f38dc7b50623
Revises: a3566b43c221
Create Date: 2026-07-16 23:40:48.871991
"""
from alembic import op
import sqlalchemy as sa


revision = 'f38dc7b50623'
down_revision = 'a3566b43c221'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('workspace_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id', name='uq_member')
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_workspace_id'), ['workspace_id'], unique=False)

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_collections_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_connections_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_datasets_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_environments_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_flows_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_prompts_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_unique_constraint('uq_prompt_key', ['workspace_id', 'key'])
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_requests_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_runs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_foreign_key(None, 'workspaces', ['workspace_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_runs_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_requests_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('prompts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('uq_prompt_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_prompts_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('flows', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_flows_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('environments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_environments_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_datasets_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_connections_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('collections', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_collections_workspace_id'))
        batch_op.drop_column('workspace_id')

    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_user_id'))

    op.drop_table('workspace_members')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_user_id'))

    op.drop_table('workspaces')
    # ### end Alembic commands ###
