import { DatasetResult } from "./api";

function esc(s: any): string {
  return String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c] as string));
}

function requestSummary(req: any): string {
  if (req.type === "prompt") return `prompt · ${esc(req.model || "")}`;
  if (req.type === "tool") return `tool · ${esc(req.tool || "")}`;
  if (req.type === "agent") return `agent · ${esc(req.method || "POST")} ${esc(req.path || "")}`;
  return esc(req.type);
}

function outputPeek(row: any): string {
  const v = row.output != null ? row.output : row.text;
  const s = typeof v === "object" ? JSON.stringify(v) : String(v ?? "");
  return esc(s.length > 400 ? s.slice(0, 400) + "…" : s);
}

export function datasetReportHtml(request: any, result: DatasetResult): string {
  const now = new Date().toLocaleString();
  const { passed, total } = result.summary;
  const rate = total ? Math.round((passed / total) * 100) : 0;
  const allPass = passed === total && total > 0;

  const rows = result.rows.map((r) => {
    const asserts = (r.assertions || []).map((a: any) =>
      `<div class="a ${a.ok ? "ok" : "no"}"><span>${a.ok ? "✓" : "✕"}</span> <b>${esc(a.name)}</b> <i>${esc(a.type)}</i> — ${esc(a.detail)}</div>`).join("");
    return `<div class="row ${r.pass ? "ok" : "no"}">
      <div class="rh"><span class="dot"></span><b>${esc(r.name)}</b><span class="st">${esc(r.status)}</span><span class="ms">${r.duration_ms} ms</span></div>
      ${asserts ? `<div class="asserts">${asserts}</div>` : ""}
      <pre class="out">${outputPeek(r)}</pre>
    </div>`;
  }).join("");

  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ProveKit · Eval Report</title>
<style>
:root{--bg:#0c0d12;--pan:#14161d;--pan2:#1a1d26;--bd:#262a36;--tx:#e7e9f0;--mu:#8b91a4;--fa:#5c6274;--ac:#7c6cff;--ok:#2fd9a5;--no:#ff6b6b;--mono:ui-monospace,"SF Mono",Menlo,monospace}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--tx);font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;font-size:14px;line-height:1.55}
.wrap{max-width:860px;margin:0 auto;padding:40px 24px 80px}
.brand{display:flex;align-items:center;gap:9px;font-weight:700;font-size:17px}
.logo{width:26px;height:26px;border-radius:7px;display:grid;place-items:center;background:linear-gradient(135deg,var(--ac),#4b3fd6)}
.brand b{color:#a99bff}.sub{color:var(--fa);font-family:var(--mono);font-size:12px;margin-left:auto}
.hero{display:flex;align-items:center;gap:24px;margin:26px 0;padding:22px 24px;background:var(--pan);border:1px solid var(--bd);border-radius:14px}
.rate{font-size:44px;font-weight:800;line-height:1}.rate.ok{color:var(--ok)}.rate.no{color:var(--no)}
.pill{font-family:var(--mono);font-size:12px;padding:4px 11px;border-radius:20px;background:var(--pan2);color:var(--mu)}
.meta{color:var(--mu);font-size:12.5px;margin-top:4px}
.row{background:var(--pan);border:1px solid var(--bd);border-radius:12px;padding:14px 16px;margin-bottom:10px}
.row.ok{border-color:rgba(47,217,165,.3)}.row.no{border-color:rgba(255,107,107,.35)}
.rh{display:flex;align-items:center;gap:10px}.rh b{font-size:14px}.dot{width:9px;height:9px;border-radius:50%}
.row.ok .dot{background:var(--ok)}.row.no .dot{background:var(--no)}
.st{font-family:var(--mono);font-size:11px;color:var(--fa)}.ms{margin-left:auto;font-family:var(--mono);font-size:11px;color:var(--mu)}
.asserts{margin:10px 0 6px;display:grid;gap:4px}
.a{font-family:var(--mono);font-size:11.5px;color:var(--mu)}.a b{color:var(--tx);font-weight:600}.a i{color:var(--fa);font-style:normal}
.a.ok span{color:var(--ok)}.a.no span{color:var(--no)}
.out{font-family:var(--mono);font-size:11px;color:var(--mu);background:var(--pan2);border-radius:8px;padding:9px 11px;margin:8px 0 0;white-space:pre-wrap;word-break:break-word;overflow:auto}
.foot{color:var(--fa);font-size:11.5px;text-align:center;margin-top:34px;font-family:var(--mono)}
</style></head><body><div class="wrap">
<div class="brand"><span class="logo">◇</span>Agent<b>Man</b> · Eval Report<span class="sub">${esc(now)}</span></div>
<div class="hero">
  <div><div class="rate ${allPass ? "ok" : "no"}">${rate}%</div></div>
  <div>
    <div style="font-size:18px;font-weight:700">${passed} / ${total} rows passed</div>
    <div class="meta">${requestSummary(request)}</div>
  </div>
  <span class="pill" style="margin-left:auto">${result.rows.length} rows</span>
</div>
${rows}
<div class="foot">Generated by ProveKit — Postman for agents</div>
</div></body></html>`;
}

export function downloadHtml(filename: string, html: string) {
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
